# AI Talent & Career Intelligence

### Phase 1: Data Intelligence Audit

### Objective

Perform a comprehensive audit of the AI Workforce Intelligence dataset to understand:

- Dataset structure
- Data quality
- Feature inventory
- Business relevance
- Analysis opportunities

#### Analyst

Chandu

### Section 1: Environment Setup

In [31]:
# Import Libraries

import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings("ignore")

# Configure Display Settings

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", None)

# Display Environment Information

print("\nEnvironment Information")
print("-" * 22)

print(f"Pandas Version : {pd.__version__}")
print(f"NumPy Version  : {np.__version__}")

Environment Information
----------------------
Pandas Version : 3.0.3
NumPy Version  : 2.4.6

### Section 2: Dataset Loading

In [32]:
# Load Dataset (Global AI Jobs)

DATA_PATH = "../data/raw/ai_jobs.csv"

df = pd.read_csv(DATA_PATH)

print("\nDataset Loaded Successfully")

Dataset Loaded Successfully

### Section 3: Dataset Snapshot

In [33]:
# Dataset Shape Analysis

print("\nDataset Shape")

print("-" * 16)

rows, columns = df.shape

print(f"Rows    : {rows:,}")
print(f"Columns : {columns}")

print("-" * 16)

# Dataset Preview

display(df.head())

Dataset Shape
----------------
Rows    : 90,000
Columns : 35
----------------

,id,country,job_role,ai_specialization,experience_level,experience_years,salary_usd,bonus_usd,education_required,industry,company_size,interview_rounds,year,work_mode,weekly_hours,company_rating,job_openings,hiring_difficulty_score,layoff_risk,ai_adoption_score,company_funding_billion,economic_index,ai_maturity_years,offer_acceptance_rate,tax_rate_percent,vacation_days,skill_demand_score,automation_risk,job_security_score,career_growth_score,work_life_balance_score,promotion_speed,salary_percentile,cost_of_living_index,employee_satisfaction
0,1,UAE,Machine Learning Engineer,Reinforcement Learning,Entry,0,66465,5395,Master,Automotive,Small,7,2020,Remote,44.7,3.67,10,52.765351,0.404,91,3.30,78.65,13,60.58,20.8,27,12,76,57,65,73,15,55,1.23,76
1,2,USA,AI Engineer,LLM,Entry,1,75507,11713,Bootcamp,Retail,Small,3,2021,Onsite,48.9,4.26,27,53.114580,0.387,71,4.39,62.14,13,75.80,28.4,27,54,29,69,60,51,15,58,0.87,67
2,3,Brazil,Research Scientist,Analytics,Entry,0,41660,5268,PhD,Healthcare,Large,3,2020,Remote,46.8,4.78,10,76.395263,0.415,69,5.04,87.47,8,62.95,12.2,13,12,49,70,59,68,37,13,2.13,61
3,4,India,Software Engineer AI,Computer Vision,Senior,6,43268,7975,Diploma,Tech,Large,2,2026,Onsite,52.2,4.34,23,59.340199,0.115,74,4.38,86.84,7,77.45,35.1,30,80,47,79,65,55,46,74,1.49,56
4,5,Germany,Machine Learning Engineer,Computer Vision,Entry,0,69119,4758,Master,Retail,Medium,2,2021,Hybrid,46.7,4.49,17,72.301128,0.311,68,6.67,79.84,7,89.86,36.1,24,82,47,64,52,69,17,21,0.87,72

### Section 4: Structural Audit

In [34]:
# Columns Audit

print("\n" + "-" * 20)
print("List of columns")
print("-" * 20 + "\n")

for index, col in enumerate(df.columns, start=1):
    print(f"{index}. {col}")

--------------------
List of columns
--------------------

1. id
2. country
3. job_role
4. ai_specialization
5. experience_level
6. experience_years
7. salary_usd
8. bonus_usd
9. education_required
10. industry
11. company_size
12. interview_rounds
13. year
14. work_mode
15. weekly_hours
16. company_rating
17. job_openings
18. hiring_difficulty_score
19. layoff_risk
20. ai_adoption_score
21. company_funding_billion
22. economic_index
23. ai_maturity_years
24. offer_acceptance_rate
25. tax_rate_percent
26. vacation_days
27. skill_demand_score
28. automation_risk
29. job_security_score
30. career_growth_score
31. work_life_balance_score
32. promotion_speed
33. salary_percentile
34. cost_of_living_index
35. employee_satisfaction

### Section 5: Data Type Analysis Audit

In [35]:
print("-" * 20)
print("DATA TYPE ANALYSIS")
print("-" * 20)

datatype_summary = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values
})

display(datatype_summary)

print("\nDatatype Counts:\n")
display(df.dtypes.value_counts())

--------------------
DATA TYPE ANALYSIS
--------------------

                     Column Data Type
0                        id     int64
1                   country       str
2                  job_role       str
3         ai_specialization       str
4          experience_level       str
5          experience_years     int64
6                salary_usd     int64
7                 bonus_usd     int64
8        education_required       str
9                  industry       str
10             company_size       str
11         interview_rounds     int64
12                     year     int64
13                work_mode       str
14             weekly_hours   float64
15           company_rating   float64
16             job_openings     int64
17  hiring_difficulty_score   float64
18              layoff_risk   float64
19        ai_adoption_score     int64
20  company_funding_billion   float64
21           economic_index   float64
22        ai_maturity_years     int64
23    offer_acceptance_rate   float64
24         tax_rate_percent   float64
25            vacation_days     int64
26       skill_demand_score     int64
27          automation_risk     int64
28       job_security_score     int64
29      career_growth_score     int64
30  work_life_balance_score     int64
31          promotion_speed     int64
32        salary_percentile     int64
33     cost_of_living_index   float64
34    employee_satisfaction     int64

Datatype Counts:

int64      18
float64     9
str         8
Name: count, dtype: int64

### Section 6: Missing Value Audit

In [36]:
# Missing Value Analysis

print("\n" + "-" * 22)
print("Missing Value Analysis")
print("-" * 22)

missing_values = df.isnull().sum()

missing_percentage = (
    df.isnull().sum() / len(df)
) * 100

missing_report = pd.DataFrame({
    "Missing Count": missing_values,
    "Missing Percentage": missing_percentage
})

display(
    missing_report.sort_values(
        by="Missing Count",
        ascending=False
    )
)

----------------------
Missing Value Analysis
----------------------

                         Missing Count  Missing Percentage
id                                   0                 0.0
country                              0                 0.0
job_role                             0                 0.0
ai_specialization                    0                 0.0
experience_level                     0                 0.0
experience_years                     0                 0.0
salary_usd                           0                 0.0
bonus_usd                            0                 0.0
education_required                   0                 0.0
industry                             0                 0.0
company_size                         0                 0.0
interview_rounds                     0                 0.0
year                                 0                 0.0
work_mode                            0                 0.0
weekly_hours                         0                 0.0
company_rating                       0                 0.0
job_openings                         0                 0.0
hiring_difficulty_score              0                 0.0
layoff_risk                          0                 0.0
ai_adoption_score                    0                 0.0
company_funding_billion              0                 0.0
economic_index                       0                 0.0
ai_maturity_years                    0                 0.0
offer_acceptance_rate                0                 0.0
tax_rate_percent                     0                 0.0
vacation_days                        0                 0.0
skill_demand_score                   0                 0.0
automation_risk                      0                 0.0
job_security_score                   0                 0.0
career_growth_score                  0                 0.0
work_life_balance_score              0                 0.0
promotion_speed                      0                 0.0
salary_percentile                    0                 0.0
cost_of_living_index                 0                 0.0
employee_satisfaction                0                 0.0

### Section 7: Empty String Validation

In [37]:
print("-" * 23)
print("EMPTY STRING VALIDATION")
print("-" * 23)

categorical_columns = df.select_dtypes(
    include="object"
).columns

for col in categorical_columns:

    empty_count = (
        df[col]
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(f"{col}: {empty_count}")

-----------------------
EMPTY STRING VALIDATION
-----------------------
country: 0
job_role: 0
ai_specialization: 0
experience_level: 0
education_required: 0
industry: 0
company_size: 0
work_mode: 0

### Section 8: Score Validation

In [38]:
# Score Validation

print("-" * 50)
print("Score Validation")
print("-" * 50)

numerical_columns = (
    df.select_dtypes(
        include=np.number
    ).columns
)

for col in numerical_columns:

    print(f"\n{col}")

    display (
        pd.DataFrame({
            "Min" : [df[col].min()],
            "Max" : [df[col].max()]
        })
    )
    # display(data)

--------------------------------------------------
Score Validation
--------------------------------------------------

id

   Min    Max
0    1  90000

experience_years

   Min  Max
0    0   19

salary_usd

     Min     Max
0  28000  300622

bonus_usd

    Min    Max
0  1404  57681

interview_rounds

   Min  Max
0    2    7

year

    Min   Max
0  2020  2026

weekly_hours

    Min   Max
0  36.0  55.0

company_rating

   Min  Max
0  3.2  4.8

job_openings

   Min  Max
0    1   50

hiring_difficulty_score

   Min    Max
0  0.0  100.0

layoff_risk

   Min    Max
0  0.0  0.588

ai_adoption_score

   Min  Max
0    1  100

company_funding_billion

   Min  Max
0  0.2  9.5

economic_index

    Min    Max
0  45.0  100.0

ai_maturity_years

   Min  Max
0    3   14

offer_acceptance_rate

    Min   Max
0  55.0  95.0

tax_rate_percent

    Min   Max
0  12.0  42.0

vacation_days

   Min  Max
0   10   30

skill_demand_score

   Min  Max
0    1  100

automation_risk

   Min  Max
0    1  100

job_security_score

   Min  Max
0   29   99

career_growth_score

   Min  Max
0   25   99

work_life_balance_score

   Min  Max
0   25   98

promotion_speed

   Min  Max
0   12   98

salary_percentile

   Min  Max
0    1  100

cost_of_living_index

   Min  Max
0  0.5  2.5

employee_satisfaction

   Min  Max
0   42   99

### Section 9: Categorical Cardinality Analysis

In [39]:
# Categorical Cardinality Analysis

print("\n" + "-" * 32)
print("Categorical Cardinality Analysis")
print("-" * 32)

cardinality_report = pd.DataFrame({
    "Column": categorical_columns,
    "Unique Values": [
        df[column].nunique()
        for column in categorical_columns
    ]
})

display(
    cardinality_report.sort_values(
        by="Unique Values",
        ascending=False
    )
)

--------------------------------
Categorical Cardinality Analysis
--------------------------------

               Column  Unique Values
0             country             12
5            industry             10
2   ai_specialization              8
1            job_role              8
6        company_size              5
4  education_required              5
3    experience_level              4
7           work_mode              3

### Section 10: Categorical Cardinality Analysis Review

In [40]:
print("-" * 39)
print("Categorical Cardinality Analysis Review")
print("-" * 39)

categorical_columns = df.select_dtypes(
    include="object"
).columns

print(f"Total Categorical Columns: {len(categorical_columns)}")

for col in categorical_columns:
    display(
        df[col]
        .value_counts()
    )

---------------------------------------
Categorical Cardinality Analysis Review
---------------------------------------
Total Categorical Columns: 8

country
Canada         7602
Australia      7589
Singapore      7583
Brazil         7545
UK             7532
UAE            7529
Netherlands    7514
Germany        7461
India          7450
France         7440
USA            7405
Japan          7350
Name: count, dtype: int64

job_role
NLP Engineer                 11412
Software Engineer AI         11333
Research Scientist           11309
Machine Learning Engineer    11263
AI Engineer                  11247
Computer Vision Engineer     11227
Data Scientist               11146
Data Analyst                 11063
Name: count, dtype: int64

ai_specialization
Computer Vision           11487
LLM                       11466
Reinforcement Learning    11261
Analytics                 11258
Generative AI             11208
MLOps                     11133
Forecasting               11115
NLP                       11072
Name: count, dtype: int64

experience_level
Senior    22680
Lead      22556
Mid       22459
Entry     22305
Name: count, dtype: int64

education_required
Bootcamp    18148
PhD         18070
Bachelor    18005
Diploma     17914
Master      17863
Name: count, dtype: int64

industry
Gaming        9190
Education     9067
Finance       9057
Energy        9017
Retail        8987
Tech          8984
Consulting    8954
Telecom       8939
Automotive    8930
Healthcare    8875
Name: count, dtype: int64

company_size
Medium        18328
Startup       18008
Enterprise    17988
Small         17919
Large         17757
Name: count, dtype: int64

work_mode
Onsite    30233
Remote    30005
Hybrid    29762
Name: count, dtype: int64

### Section 11: Duplicates Analysis

In [41]:
# Duplcate rows analysis

duplicate_count = df.duplicated().sum()

print(
    f"\nDuplicate Rows: {duplicate_count}"
)

Duplicate Rows: 0

### Section 12: Numerical Feature Analysis

In [42]:
print("\n" + "-" * 26)
print("Numerical Feature Analysis")
print("-" * 26)

numerical_columns = (
    df.select_dtypes(
        include=np.number
    ).columns
)

print(f"Numerical Features : {len(numerical_columns)}")

display(
    df[numerical_columns]
    .describe()
    .T
    .round(2)
)

--------------------------
Numerical Feature Analysis
--------------------------
Numerical Features : 27

,count,mean,std,min,25%,50%,75%,max
id,90000.0,45000.50,25980.91,1.0,22500.75,45000.50,67500.25,90000.00
experience_years,90000.0,7.03,5.89,0.0,2.00,6.00,12.00,19.00
salary_usd,90000.0,96546.25,43935.48,28000.0,64676.75,87544.00,123906.00,300622.00
bonus_usd,90000.0,13028.42,7886.74,1404.0,7104.75,11279.00,16997.25,57681.00
interview_rounds,90000.0,4.50,1.70,2.0,3.00,4.00,6.00,7.00
year,90000.0,2023.00,2.00,2020.0,2021.00,2023.00,2025.00,2026.00
weekly_hours,90000.0,45.48,5.48,36.0,40.70,45.50,50.20,55.00
company_rating,90000.0,4.00,0.46,3.2,3.60,4.00,4.40,4.80
job_openings,90000.0,17.52,7.85,1.0,12.00,17.00,23.00,50.00
hiring_difficulty_score,90000.0,55.03,17.90,0.0,42.88,55.07,67.12,100.00
layoff_risk,90000.0,0.18,0.13,0.0,0.08,0.14,0.28,0.59
ai_adoption_score,90000.0,71.38,13.77,1.0,62.00,71.00,81.00,100.00
company_funding_billion,90000.0,4.85,2.68,0.2,2.53,4.84,7.17,9.50
economic_index,90000.0,72.52,15.88,45.0,58.73,72.58,86.26,100.00
ai_maturity_years,90000.0,8.52,3.45,3.0,6.00,9.00,12.00,14.00
offer_acceptance_rate,90000.0,75.01,11.51,55.0,65.07,75.00,84.99,95.00
tax_rate_percent,90000.0,27.01,8.66,12.0,19.50,27.00,34.50,42.00
vacation_days,90000.0,19.99,6.07,10.0,15.00,20.00,25.00,30.00
skill_demand_score,90000.0,50.46,28.85,1.0,25.00,51.00,75.00,100.00
automation_risk,90000.0,50.36,28.85,1.0,25.00,50.00,75.00,100.00
job_security_score,90000.0,75.56,11.32,29.0,68.00,77.00,84.00,99.00
career_growth_score,90000.0,57.20,12.90,25.0,48.00,57.00,66.00,99.00
work_life_balance_score,90000.0,69.15,13.21,25.0,59.00,69.00,79.00,98.00
promotion_speed,90000.0,38.44,18.43,12.0,24.00,37.00,51.00,98.00
salary_percentile,90000.0,50.54,28.89,1.0,25.00,51.00,76.00,100.00
cost_of_living_index,90000.0,1.50,0.58,0.5,1.01,1.51,2.00,2.50
employee_satisfaction,90000.0,72.73,8.12,42.0,67.00,73.00,78.00,99.00

### Section 13: Numerical Validation Report

In [43]:
# Numerical Validation Report

print("\n" + "-" * 27)
print("Numerical Validation Report")
print("-" * 27)

numerical_columns = (
    df.select_dtypes(
        include=np.number
        )
        .columns
    )

validation_report = []

for column in numerical_columns:

    validation_report.append({

        "Column"            :   column,
        "Minimum Value"     :   df[column].min(),
        "Maximum Value"     :   df[column].max(),
        "Negative Values"   :   (df[column] < 0).sum()

    })

validation_report_pd = pd.DataFrame(
    validation_report
)

display(validation_report_pd)

---------------------------
Numerical Validation Report
---------------------------

                     Column  Minimum Value  Maximum Value  Negative Values
0                        id            1.0      90000.000                0
1          experience_years            0.0         19.000                0
2                salary_usd        28000.0     300622.000                0
3                 bonus_usd         1404.0      57681.000                0
4          interview_rounds            2.0          7.000                0
5                      year         2020.0       2026.000                0
6              weekly_hours           36.0         55.000                0
7            company_rating            3.2          4.800                0
8              job_openings            1.0         50.000                0
9   hiring_difficulty_score            0.0        100.000                0
10              layoff_risk            0.0          0.588                0
11        ai_adoption_score            1.0        100.000                0
12  company_funding_billion            0.2          9.500                0
13           economic_index           45.0        100.000                0
14        ai_maturity_years            3.0         14.000                0
15    offer_acceptance_rate           55.0         95.000                0
16         tax_rate_percent           12.0         42.000                0
17            vacation_days           10.0         30.000                0
18       skill_demand_score            1.0        100.000                0
19          automation_risk            1.0        100.000                0
20       job_security_score           29.0         99.000                0
21      career_growth_score           25.0         99.000                0
22  work_life_balance_score           25.0         98.000                0
23          promotion_speed           12.0         98.000                0
24        salary_percentile            1.0        100.000                0
25     cost_of_living_index            0.5          2.500                0
26    employee_satisfaction           42.0         99.000                0

### Section 14: Outliers Investigation

In [44]:
# Outliers Investigation

print("-" * 50)
print("Outliers Investigation")
print("-" * 50)

outlier_summary = []

for col in numerical_columns:

    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)

    iqr = q3 - q1

    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    outliers = (
        (
            df[col] < lower
        )
        |
        (
            df[col] > upper
        )
    ).sum()

    outlier_summary.append(
        [col, outliers]
    )

outlier_report = pd.DataFrame(
    outlier_summary,
    columns=[
        "Column",
        "Outlier Count"
    ]
)

display(
    outlier_report.sort_values(
        by="Outlier Count",
        ascending=False
    )
)

--------------------------------------------------
Outliers Investigation
--------------------------------------------------

                     Column  Outlier Count
3                 bonus_usd           2748
2                salary_usd           1007
26    employee_satisfaction            515
23          promotion_speed            478
11        ai_adoption_score            325
9   hiring_difficulty_score            308
8              job_openings            275
20       job_security_score            267
21      career_growth_score            111
22  work_life_balance_score             18
10              layoff_risk              1
7            company_rating              0
4          interview_rounds              0
5                      year              0
6              weekly_hours              0
0                        id              0
1          experience_years              0
13           economic_index              0
12  company_funding_billion              0
18       skill_demand_score              0
17            vacation_days              0
16         tax_rate_percent              0
15    offer_acceptance_rate              0
14        ai_maturity_years              0
19          automation_risk              0
24        salary_percentile              0
25     cost_of_living_index              0

## Final Audit Summary

In [45]:
audit_summary = pd.DataFrame({

    "Metric": [
        "Rows",
        "Columns",
        "Missing Values",
        "Duplicate Rows",
        "Numerical Features",
        "Categorical Features"
    ],

    "Value": [
        len(df),
        len(df.columns),
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        len(numerical_columns),
        len(categorical_columns)
    ]
})

print("\n" + "-" * 27)
print("Final Dataset Audit Summary")
print("-" * 27)

display(audit_summary)

---------------------------
Final Dataset Audit Summary
---------------------------

                 Metric  Value
0                  Rows  90000
1               Columns     35
2        Missing Values      0
3        Duplicate Rows      0
4    Numerical Features     27
5  Categorical Features      8

## Business Feature Classification

| Domain                 | Columns                    |
| ---------------------- | -------------------------- |
| Career Intelligence    | job_role, experience_level |
| Salary Intelligence    | salary_usd, bonus_usd      |
| Skill Intelligence     | ai_specialization          |
| Workforce Intelligence | job_openings               |
| Hiring Intelligence    | hiring_difficulty_score    |

### Phase 1 Conclusion

### Key Findings

- Dataset Contains 90,000 Records
- Dataset Contains 35 Features
- No Missing Values Detected
- No Duplicate Records Detected
- Dataset Appears Highly Curated
- Multiple Workforce Intelligence Opportunities Identified

### Readiness Assessment

The Dataset Has Successfully Passed Initial Data Intelligence Audit And Is Ready For Data Preparation And Feature Engineering.