In [ ]:
# Import Libraries

import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings("ignore")

# Configure Display Settings

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", None)

# Display Environment Information

print("\nEnvironment Information")
print("-" * 22)

print(f"Pandas Version : {pd.__version__}")
print(f"NumPy Version  : {np.__version__}")

In [ ]:
# Load Dataset (Global AI Jobs)

DATA_PATH = "../data/processed/cleaned_ai_jobs.csv"

df = pd.read_csv(DATA_PATH)

print("\nDataset Loaded Successfully")

In [ ]:
# Dataset Shape Analysis

print("\nDataset Shape")

print("-" * 16)

rows, columns = df.shape

print(f"Rows    : {rows:,}")
print(f"Columns : {columns}")

print("-" * 16)

# Dataset Preview

display(df.head())

In [ ]:
df.groupby("ai_specialization")["salary_usd"].max().round(2)
df.groupby("job_role")["salary_usd"].max().round(2)
df.groupby("country")["salary_usd"].max().sort_values(ascending=False)
df.groupby("hiring_difficulty_score")["salary_usd"].max().sort_values(ascending=False).head()
df.groupby("hiring_difficulty_score")["salary_usd"].min().sort_values(ascending=False).head()
df.groupby("experience_level")["salary_usd"].max().round(2).sort_values(ascending=False)
df.groupby("experience_years")["salary_usd"].max().round(2).sort_values()
df.groupby("industry")["salary_usd"].max().round(2).sort_values(ascending=False)
df.groupby("education_required")["salary_usd"].max().round(2).sort_values(ascending=False)

### Analysis 1
### Experience Level vs Salary

In [ ]:
salary_by_experience_level = (
    df.groupby(
        "experience_level"
    )["salary_usd"]
    .agg([
        "count",
        "mean",
        "median",
        "min",
        "max",
        "std"
    ])
    .round(2)
    .sort_values(
        by="mean",
        ascending=False
    )
)

salary_by_experience_level

### Analysis 2
### Country vs Salary

In [36]:
salary_by_country = (
    df.groupby(
        "country"
    )["salary_usd"]
    .agg([
        "count",
        "mean",
        "median",
        "min",
        "max",
        "std"
    ])
    .round(2)
    .sort_values(
        by="mean",
        ascending=False
    )
)

salary_by_country

             count       mean    median    min     max       std
country
USA           7405  132995.21  121887.0  47057  300622  49793.07
Singapore     7583  116954.73  107137.0  41399  263559  43115.37
Australia     7589  110549.81  101083.0  39026  246866  41155.81
Canada        7602  108671.05   99709.5  38547  247266  40260.85
UK            7532  102826.24   93746.0  36685  232850  37907.95
Netherlands   7514  102379.05   93740.5  36263  232080  38322.35
Germany       7461  100007.78   91867.0  35436  226492  36877.81
Japan         7350   98507.66   90088.0  35079  215632  36721.88
France        7440   95170.46   88105.5  34527  215958  35279.41
UAE           7529   93507.70   86097.0  33010  210545  34266.57
Brazil        7545   53704.84   49270.0  28000  120334  19750.04
India         7450   43106.30   38511.5  28000   95348  14976.33

### Analysis 3
### AI Specialization vs Salary

In [37]:
salary_by_specialization = (
    df.groupby(
        "ai_specialization"
    )["salary_usd"]
    .agg([
        "count",
        "mean",
        "median",
        "min",
        "max",
        "std"
    ])
    .round(2)
    .sort_values(
        by="mean",
        ascending=False
    )
)

salary_by_specialization

                        count      mean   median    min     max       std
ai_specialization
Generative AI           11208  97096.78  87253.0  28000  286008  44498.96
LLM                     11466  97076.65  88086.0  28000  289776  44131.09
Analytics               11258  96905.55  87892.0  28000  288941  44111.58
MLOps                   11133  96742.07  87644.0  28000  297267  44034.49
Computer Vision         11487  96655.16  88080.0  28000  299543  43803.63
NLP                     11072  96443.81  87936.5  28000  300622  43560.48
Forecasting             11115  96010.56  87063.0  28000  284840  43603.29
Reinforcement Learning  11261  95423.81  86191.0  28000  288779  43711.79

### Analysis 4
### Industry vs Salary

In [38]:
salary_by_industry = (
    df.groupby(
        "industry"
    )["salary_usd"]
    .agg([
        "count",
        "mean",
        "median",
        "min",
        "max",
        "std"
    ])
    .round(2)
    .sort_values(
        by="mean",
        ascending=False
    )
)

salary_by_industry

            count      mean   median    min     max       std
industry
Retail       8987  97266.10  88285.0  28000  283182  44087.76
Gaming       9190  97265.59  88390.5  28000  286008  44088.64
Automotive   8930  96841.79  87736.0  28000  300622  44245.74
Tech         8984  96606.28  87234.0  28000  289000  43775.62
Education    9067  96587.20  87428.0  28000  297267  43982.84
Consulting   8954  96545.42  87512.0  28000  283321  43989.42
Healthcare   8875  96289.60  87739.0  28000  299543  43873.83
Finance      9057  96223.29  87121.0  28000  275933  43900.68
Telecom      8939  95959.90  86918.0  28000  288779  43770.27
Energy       9017  95861.07  86714.0  28000  279406  43632.31

### Analysis 5
### Hiring Difficulty vs Salary

In [40]:
salary_by_hiring_difficulty = (
    df.groupby(
        "hiring_difficulty_score"
    )["salary_usd"]
    .agg([
        "count",
        "mean",
        "median",
        "min",
        "max",
        "std"
    ])
    .round(2)
    .sort_values(
        by="mean",
        ascending=False
    ).head()
)

salary_by_hiring_difficulty

                         count      mean    median     min     max  std
hiring_difficulty_score
15.26                        1  252741.0  252741.0  252741  252741  NaN
9.53                         1  251684.0  251684.0  251684  251684  NaN
16.08                        1  238350.0  238350.0  238350  238350  NaN
1.99                         1  232601.0  232601.0  232601  232601  NaN
93.71                        1  231676.0  231676.0  231676  231676  NaN

### Analysis 6
### Education vs Salary

In [41]:
salary_by_education = (
    df.groupby(
        "education_required"
    )["salary_usd"]
    .agg([
        "count",
        "mean",
        "median",
        "min",
        "max",
        "std"
    ])
    .round(2)
    .sort_values(
        by="mean",
        ascending=False
    )
)

salary_by_education

                    count      mean   median    min     max       std
education_required
Bootcamp            18148  97206.04  88233.0  28000  297267  44188.73
Bachelor            18005  97026.41  87710.0  28000  288941  44164.25
Diploma             17914  96283.37  87356.5  28000  289000  43844.91
Phd                 18070  96131.33  87465.0  28000  300622  43525.85
Master              17863  96075.31  86946.0  28000  284840  43941.39

### Analysis 7
### Job Role vs Salary

In [42]:
salary_by_job_role = (
    df.groupby(
        "job_role"
    )["salary_usd"]
    .agg([
        "count",
        "mean",
        "median",
        "min",
        "max",
        "std"
    ])
    .round(2)
    .sort_values(
        by="mean",
        ascending=False
    )
)

salary_by_job_role

                           count       mean   median    min     max       std
job_role
Research Scientist         11309  109797.50  99659.0  28000  300622  48013.57
Machine Learning Engineer  11263  102121.80  93257.0  28000  277408  44699.42
Computer Vision Engineer   11227  101303.94  91730.0  28000  276175  44656.17
NLP Engineer               11412   99745.32  90826.0  28000  272950  43797.47
AI Engineer                11247   97974.71  88501.0  28000  268390  42883.10
AI Software Engineer       11333   97375.53  88723.0  28000  263226  42572.31
Data Scientist             11146   94029.90  85501.5  28000  255231  41243.03
Data Analyst               11063   69429.27  62657.0  28000  187484  29706.67